{
 "title": "Load Tester - Actions",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Clients connected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(rc_load_connected)", "legendFormat": "Connected" },
    {
     "expr": "sum(rc_load_login_count{status=\"success\"})",
     "legendFormat": "Logged in"
    },
    {
     "expr": "sum(rc_load_login_count{status=\"error\"})",
     "legendFormat": "Login error"
    }
   ]
  },
  {
   "title": "Login time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rc_load_login[3m]))",
     "legendFormat": "Login time"
    }
   ]
  },
  {
   "title": "Actions per 3 minutes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rc_actions_count{status=\"success\"}) by (action)",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "sum(rc_actions_count{status=\"error\"}) by (action)",
     "legendFormat": "error {{action}}"
    }
   ]
  },
  {
   "title": "Actions rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rc_actions_count{status=\"success\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "sum(increase(rc_actions_count{status=\"error\"}[5m])) by (action)",
     "legendFormat": "error {{action}}"
    }
   ]
  },
  {
   "title": "Action times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rc_actions[3m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Messages sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rc_load_messages_count{status=\"success\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rc_load_messages_count{status=\"error\"}) by (instance)",
     "legendFormat": "errors {{instance}}"
    }
   ]
  },
  {
   "title": "Messages per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rc_load_messages[5m]))",
     "legendFormat": "Messages per second"
    }
   ]
  }
 ]
}